name: progress_builder
description: A simple wrapper for asynchronous actions with progress/loading indicators and error handling.
version: 1.0.3
homepage: https://github.com/apexlabs-ai/progress_builder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  lints: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
